# Generated by Django 5.0.4 on 2024-05-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactdb',
        ),
    ]
